name: Release

on:
  push:
    tags:
      - "v*"

concurrency: ${{ github.workflow }}-${{ github.ref }}

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
      id-token: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Bun
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest

      - name: Install dependencies
        run: bun install --frozen-lockfile

      - name: Build packages
        run: bun run build

      - name: Run tests
        run: bun test

      - name: Extract version from tag
        id: version
        run: echo "VERSION=${GITHUB_REF#refs/tags/v}" >> $GITHUB_OUTPUT

      - name: Publish to npm
        run: bun run publish
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}

      - name: Create GitHub Release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref_name }}
          release_name: Release ${{ github.ref_name }}
          body: |
            ## Release ${{ steps.version.outputs.VERSION }}

            Published npm packages for version ${{ steps.version.outputs.VERSION }}

            ### Installation
            ```bash
            npm install @kuuzuki-ge/core@${{ steps.version.outputs.VERSION }}
            ```

            ### Packages
            - @kuuzuki-ge/core
            - @kuuzuki-ge/cli
            - @kuuzuki-ge/mcp-server
            - @kuuzuki-ge/pixel-art-generator
            - @kuuzuki-ge/butler-deploy
            - @kuuzuki-ge/tui-editor
          draft: false
          prerelease: ${{ contains(github.ref_name, 'alpha') || contains(github.ref_name, 'beta') || contains(github.ref_name, 'rc') }}
  validate-packages:
    name: Validate Published Packages
    runs-on: ubuntu-latest
    needs: release

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Bun
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest

      - name: Test package installation from npm
        run: |
          # Wait a bit for npm to propagate
          sleep 30

          # Test installing the published package
          mkdir test-published
          cd test-published
          npm init -y
          npm install @kuuzuki-ge/core@latest

          # Verify the package works
          node -e "
            const engine = require('@kuuzuki-ge/core');
            console.log('Package installed and imported successfully');
            console.log('Available exports:', Object.keys(engine));
          "

      - name: Update documentation
        run: |
          echo "📦 New version published successfully!" >> $GITHUB_STEP_SUMMARY
          echo "Users can now install with: \`npm install @kuuzuki-ge/core@latest\`" >> $GITHUB_STEP_SUMMARY
